Profile3
TestAutomarionLab6/TestProject pull request #35
Opened 2018-09-26 11:06 UTC by hrafov

2018-09-27 11:47 UTC, KnazevValeriy submitted a review, later dismissed

2018-09-27 13:04 UTC, MysiukR submitted a review, later dismissed

2018-09-28 12:36 UTC, old-zoomer requested changes

2018-09-28 12:36 UTC, mykola-zomchak commented on src/main/java/com/epam/lab/business/ProfilePageBo.java
> +	     public void getAndClickAllContactsButton() {
the same as in previous pull request

2018-09-28 13:52 UTC, hrafov commented on src/main/java/com/epam/lab/business/ProfilePageBo.java
> +	     public void getAndClickAllContactsButton() {
yes it my fault

2018-09-30 12:23 UTC, hrafov reviewed
delete 2 test

2018-10-01 08:10 UTC, old-zoomer approved these changes

2018-10-01 10:16 UTC, MysiukR approved these changes

2018-10-01 12:58 UTC, hrafov reviewed
new

2018-10-08 16:30 UTC, merged