Delete user.csv
TestAutomarionLab6/TestProject pull request #40
Opened 2018-10-02 15:50 UTC by KnazevValeriy

Deleting user.csv and adding it to .gitignor to be able to use Jenkins secret file with credentials

2018-10-02 15:55 UTC, VovaDrobko approved these changes

2018-10-02 16:15 UTC, MysiukR approved these changes

2018-10-03 11:37 UTC, old-zoomer requested changes
leave the user.csv file, as a template

2018-10-03 12:39 UTC, hrafov submitted a review, later dismissed
ok

2018-10-03 14:46 UTC, hrafov approved these changes

2018-10-08 16:31 UTC, old-zoomer approved these changes

2018-10-08 16:31 UTC, merged